### ISSUE TITLE
dynamic linking against regex_macros causes problems unless LD_LIBRARY_PATH is set

### ISSUE THREAD

**Issue by mriehl** [ogham/rust-ansi-term#1]
While trying to get `exa` to build I encounter

```
target/exa: error while loading shared libraries: libregex_macros-bdbdbfedad0748ac.so: cannot open shared object file: No such file or directory
```
It only works if I add the `target/deps` folder to the LD_LIBRARY_PATH.

This seems related to [rust#21861](https://github.com/rust-lang/rust/issues/21861).

**Comment by mriehl** [comment]
I forgot to mention that I'm reporting the issue here since it's rust-ansi-term's `Cargo.toml` that lists regex as a dependency.

**Comment by ogham** [comment]
Which version of Rust are you using? It works for me on `rustc 1.0.0-nightly (f1398d273 2015-01-31 20:21:02 +0000)`, but I'm a couple of days behind.

**Comment by mriehl** [comment]
I rustup'd today, so that might be it:

```bash
$ rustc --version
rustc 1.0.0-nightly (eaf4c5c78 2015-02-02 15:04:54 +0000)
```

**Comment by mriehl** [comment]
Though the issue I linked occured with `rustc 1.0.0-nightly (1d00c54 2015-01-30 19:56:34 +0000)` which is older than yours.
Is it possible you have set a `LD_LIBRARY_PATH` on your machine?

**Comment by ogham** [comment]
Hey, I've tried building exa on Debian (eaf4c5c78) and I get this same error.

**Comment by ogham** [comment]
(no `LD_LIBRARY_PATH`)

**Comment by ogham** [comment]
I believe https://github.com/ogham/rust-ansi-term/commit/1c331bbfe9ed171061a988d7f0d0745ffb9451d8 should fix it. Could you please do me a favour and see if it works for you?

**Comment by mriehl** [comment]
yup, works like a charm now.

Thanks!!

**Comment by ogham** [comment]
Thank you too!
