### ISSUE TITLE
fix some ESC codes

### ISSUE THREAD

**Issue by bestouff** [ogham/rust-ansi-term#17]
Hi,

According to various [docs](https://en.wikipedia.org/wiki/ANSI_escape_code) on the web, and to some tests I did on GNOME-terminal and XTerm, some of the codes you use are wrong. Could you fix them ?
* 6 is another blink (useless)
* 7 is reverse
* 8 is hidden

I can do a PR if you prefer.

**Comment by ogham** [comment]
We might be hitting the limits of which terminals support what! I know that I've seen number 6 (blink) actually rendered as reverse on terminals that don't support it. But you're right in that it should really support the standard, if there is one.

I'm at work atm so can't re-test on the ones I was using (OS X Terminal and iTerm) until later. Will update with results.

**Comment by joshtriplett** [comment]
http://invisible-island.net/xterm/ctlseqs/ctlseqs.html (search for "CSI Pm m") doesn't list '6' at all, and it sounds like terminals differ in its interpretation, so it doesn't seem safe to use.  '7' means "reverse video", and '8' means "hidden".

I'll attach a pull request, which I've tested locally with multiple terminals.

**Comment by ogham** [comment]
This will be released in v0.8.0

**Comment by bestouff** [comment]
Perfect thanks !
