### ISSUE TITLE
Cannot browse online documentation

### ISSUE THREAD

**Issue by xitep** [ogham/rust-ansi-term#22]
It seems the certificate for the server the [rustdocs are hosted on as linked by the README](https://ogham.rustdocs.org/ansi_term) has expired some days ago:

```
> curl -I https://ogham.rustdocs.org/ansi_term
curl: (60) SSL certificate problem: certificate has expired
...
```

**Comment by ogham** [comment]
erk

**Comment by ogham** [comment]
I changed the links to use docs.rs — it doesn't work right now but will soon when it regens the docs. Thanks for pointing it out!
