### ISSUE TITLE
don't rely on GetLastError() to detect errors in enable_ansi_support

### ISSUE THREAD

**Issue by galich** [ogham/rust-ansi-term#42]
https://github.com/ogham/rust-ansi-term/blob/36b0ff39c7a7bbe4c5487fa7e040d357b98e6592/src/windows.rs#L20-L36

`GetStdHandle()` can return valid handle and GetLastError() will return ERROR_NOT_SUPPORTED (50). Error must be checked only when GetStdHandle() returns INVALID_HANDLE_VALUE (-1). It happens when GUI app creates console via AllocConsole() and tries to call enable_ansi_support().

`GetConsoleMode()` and `SetConsoleMode()` return 0 (FALSE) when they fail, GetLastError() should be called after that.

**Comment by rivy** [comment]
@ogham , any motion on this? Or the corresponding PR(#43)?

**Comment by ogham** [comment]
Thanks for going through the Windows side of this; sorry again it took so long for me to merge.
